package ru.bironix.super_food.constants;

public enum ApiError {
    AUTHENTICATION_REQUIRED,
    RESOURCE_NOT_FOUND,
    TOKEN_EXPIRED_OR_INVALID,
    DELETED_DISH_IN_ORDER,
    INCORRECT_DATA_FOR_DISH,
    INCORRECT_DATA_FOR_ADDON,
    INVALID_TOTAL_PRICE,
    USER_ALREADY_EXIST,
    INCORRECT_EMAIL_OR_PASSWORD,
    ADDRESS_REQUIRED;
}
